export const buttons = [
    { value: 'C', category: 'special' },
    { value: '%', category: 'special' },
    { value: '/', category: 'special' },
    { value: '-', category: 'normal' },
    { value: '7', category: 'number' },
    { value: '8', category: 'number' },
    { value: '9', category: 'number' },
    { value: '+', category: 'normal' },
    { value: '4', category: 'number' },
    { value: '5', category: 'number' },
    { value: '6', category: 'number' },
    { value: 'x', category: 'normal' },
    { value: '1', category: 'number' },
    { value: '2', category: 'number' },
    { value: '3', category: 'number' },
    { value: '=', category: 'wide' },
    { value: '.', category: 'number' },
    { value: '0', category: 'number' },
    { value: '00', category: 'number' },
];
